### ISSUE TITLE
Tips is for PostgreSQL while the page is for RabbitMQ

### ISSUE THREAD

**Issue by ongkhaiwei** [ibm-cloud-docs/cloud-databases#1]
https://cloud.ibm.com/docs/services/messages-for-rabbitmq?topic=cloud-databases-dashboard-backups

The tips is for PostgreSQL while the page if for RabbitMQ. Does the point in time recovery statement is still correct for RabbitMQ?

**Comment by DailyAlice** [comment]
No, the Point in time Recovery statement only applies to PostgreSQL. The link goes to the PostgreSQL docs.

**Comment by ongkhaiwei** [comment]
Alright. because it is misleading. Putting a postgresql related link in RabbitMQ section.
