### ISSUE TITLE
Log analysis region eu-de is not available as claimed in this documentation

### ISSUE THREAD

**Issue by uwitzig** [ibm-cloud-docs/cloud-databases#2]
https://cloud.ibm.com/docs/services/databases-for-postgresql?topic=cloud-databases-logging claims that log analysis region eu-de is available. This is a bug, its not available, please correct this documentation.

For your reference case: CS1399109

**Comment by DailyAlice** [comment]
Unfortunately, I cannot see that case. Log Analysis with LogDNA is available in `eu-de`. https://cloud.ibm.com/docs/services/Log-Analysis-with-LogDNA?topic=LogDNA-regions
And PostgreSQL
