### ISSUE TITLE
'cluster-service-bind' is not a registered command. See 'ibmcloud cs help'.

### ISSUE THREAD

**Issue by mohammadasim** [ibm-cloud-docs/cloud-databases#4]
I am trying to bind a Postgres service to my kubernetes cluster. I had problem with creating the key. IBM engineer told me to upgrade the ibmcloud binaries which I did, but now the cluster-bind-command is not being recognized. I am following the example in IBM cloud. If the functionality has changed, I think it is every important that the docs are updated so we can have access to the latest features. I will really appreciate, if I could get some help with this.
[Link to docs](https://cloud.ibm.com/docs/databases-for-postgresql?topic=cloud-databases-tutorial-k8s-app)
```
ibmcloud ks cluster-service-bind help
FAILED
'cluster-service-bind' is not a registered command. See 'ibmcloud cs help'.
```
`ibmcloud version
ibmcloud version 1.1.0+cc908fe-2020-04-29T09:33:25+00:00`

**Comment by DailyAlice** [comment]
hmmm...it looks like according to the IKS CLI docs it might be that the command has changed to `ibmcloud ks cluster service bind`. https://cloud.ibm.com/docs/containers?topic=containers-cli-plugin-kubernetes-service-cli#cs_cluster_service_bind

See if that helps in the short term. I can look into testing and updating soon. Thanks!

**Comment by acdntlpoet** [comment]
Closing as DailyAlice updated this command (as noted previously) approximately 4 months ago in the public docs.
